// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1X_KOg_SpwjldPby1ceIMoHti58lkzg',
    appId: '1:643043133308:web:7cfea3fb432f82e33c86f9',
    messagingSenderId: '643043133308',
    projectId: 'todoist-5c823',
    authDomain: 'todoist-5c823.firebaseapp.com',
    storageBucket: 'todoist-5c823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh42G1AiXp2FvDIC-1z1cZOdcsjp2l4s',
    appId: '1:643043133308:android:be5a8112038e79703c86f9',
    messagingSenderId: '643043133308',
    projectId: 'todoist-5c823',
    storageBucket: 'todoist-5c823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0xhr9R9VE-98Tx2ttGieBvwNzHeV7xA',
    appId: '1:643043133308:ios:3a762f1717fe27893c86f9',
    messagingSenderId: '643043133308',
    projectId: 'todoist-5c823',
    storageBucket: 'todoist-5c823.appspot.com',
    iosBundleId: 'com.example.todoist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0xhr9R9VE-98Tx2ttGieBvwNzHeV7xA',
    appId: '1:643043133308:ios:3a762f1717fe27893c86f9',
    messagingSenderId: '643043133308',
    projectId: 'todoist-5c823',
    storageBucket: 'todoist-5c823.appspot.com',
    iosBundleId: 'com.example.todoist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN1X_KOg_SpwjldPby1ceIMoHti58lkzg',
    appId: '1:643043133308:web:35e8490d207ea7883c86f9',
    messagingSenderId: '643043133308',
    projectId: 'todoist-5c823',
    authDomain: 'todoist-5c823.firebaseapp.com',
    storageBucket: 'todoist-5c823.appspot.com',
  );
}
